openapi: 3.0.3
info:
  title: Generated API
  description: A description of the generated API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: Successful operation
  /authenticate:
    post:
      responses:
        '200':
          description: Successful operation
  /channels:
    get:
      responses:
        '200':
          description: Successful operation
    post:
      responses:
        '200':
          description: Successful operation
  /channels/{channel_id}:
    get:
      parameters:
      - name: channel_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
    delete:
      parameters:
      - name: channel_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
  /channels/{channel_id}/invite:
    get:
      parameters:
      - name: channel_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
    post:
      parameters:
      - name: channel_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
  /health:
    get:
      responses:
        '200':
          description: Successful operation
  /messages:
    get:
      responses:
        '200':
          description: Successful operation
    post:
      responses:
        '200':
          description: Successful operation
  /messages/{message_id}:
    delete:
      parameters:
      - name: message_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
    patch:
      parameters:
      - name: message_id
        in: path
        description: some description
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
